# Site settings
title: Shop01-4rivers
email: johann.belau@4rivers.de
url: https://shop01.4rivers.de
description: "überall Mobil sein"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#1b1b1b'
  links: '#219ab3'

# Footer settings
footer: 4 Rivers GmbH
info: Impressum
infoLink: https://www.4rivers.de/impressum

googleForm: https://docs.google.com/forms/d/e/1FAIpQLSevotutSFa-ad9k8cQF6mLtK4_htEDsb7J0zmFX9wKxX968yA/viewform

# Build settings
markdown: kramdown
permalink: pretty
